//! VAKED Swarm · Genesis: 7c242080 · Anti-Gravity Exporter
//! Core Onboarding Norms:
//! 1. DERIVE, NEVER ASSERT: Mechanically verify all claims.
//! 2. HONESTY AT THE ARTIFACT: No fabricated metrics; document residuals.
//! 3. EXTERNAL & FAILABLE VERIFY: Seals live outside the verified codebase.
//! 4. OWNER-GATED EFFECT: Peter has merge/run authority via labels.
//! 5. NO BUILD ON DEV MACHINE: Build/verify locally, compile on CI.
//! 6. TOKEN DISCIPLINE: Keep context compact; offload bulk work.
//! 7. GRAMMAR BEFORE CODE: Design and plan via RFCs first.

const std = @import("std");
const graph = @import("graph.zig");

pub const GENESIS = "7c242080";

pub fn toVaked(a: std.mem.Allocator, g: graph.Graph) ![]u8 {
    var buf: std.ArrayList(u8) = .empty;
    errdefer buf.deinit(a);
    try buf.appendSlice(a, "# generated by anti-gravity CLI\n");
    try buf.appendSlice(a, "# Genesis: ");
    try buf.appendSlice(a, GENESIS);
    try buf.appendSlice(a, "\n\n");

    for (g.nodes.items) |n| {
        try buf.appendSlice(a, "node ");
        try buf.appendSlice(a, n.name);
        try buf.appendSlice(a, "\n");
    }

    for (g.edges.items) |e| {
        try buf.appendSlice(a, "edge ");
        try buf.appendSlice(a, e.from);
        try buf.appendSlice(a, " -> ");
        try buf.appendSlice(a, e.to);
        if (e.trust > 0) {
            try buf.appendSlice(a, " trust ");
            const trust_str = try std.fmt.allocPrint(a, "{d}", .{e.trust});
            defer a.free(trust_str);
            try buf.appendSlice(a, trust_str);
        }
        try buf.appendSlice(a, "\n");
    }

    for (g.trusts.items) |t| {
        try buf.appendSlice(a, "trust ");
        try buf.appendSlice(a, t.node);
        try buf.appendSlice(a, "Trust {\n  score (");
        const score_str = try std.fmt.allocPrint(a, "{d}", .{t.score});
        defer a.free(score_str);
        try buf.appendSlice(a, score_str);
        try buf.appendSlice(a, ")\n}\n");
    }

    return try buf.toOwnedSlice(a);
}

pub fn sealSignature(a: std.mem.Allocator, genesis: []const u8, timestamp: i64, graph_json_without_seal: []const u8) ![]u8 {
    var h = std.crypto.hash.sha2.Sha256.init(.{});
    h.update(genesis);
    h.update(graph_json_without_seal);
    var ts_buf: [64]u8 = undefined;
    const ts_str = try std.fmt.bufPrint(&ts_buf, "{d}", .{timestamp});
    h.update(ts_str);
    var digest: [32]u8 = undefined;
    h.final(&digest);
    const hex = std.fmt.bytesToHex(digest, .lower);
    return try a.dupe(u8, &hex);
}
